# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: Whiteprint.Whiteprint
PackageVersion: 0.1.1
InstallerType: inno
Scope: user
MinimumOSVersion: 10.0.0.0
UpgradeBehavior: install
FileExtensions:
- wprint
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/l1203012/Whiteprint/releases/download/windows-v0.1.1/Whiteprint-0.1.1-Setup.exe
  InstallerSha256: E186A59D29C66AF833E277789ED609F417CF347897F148BCBBC25AC89997D7BE
  ProductCode: '{6F0B7A52-3D3E-4C77-9B58-5E1A0F7C2A91}_is1'
ManifestType: installer
ManifestVersion: 1.6.0
